# -*- eval: (cargo-minor-mode 1) -*-

[workspace]
members = ["derive"]

[package]
name = "gotham_formdata"
version = "0.0.1"
authors = ["Dominic Meiser <git@msrd0.de>"]
edition = "2018"

[dependencies]
futures-util = "0.3"
gotham = { version = "0.5", default-features = false }
gotham_formdata_derive = { version = "0.0.1", path = "derive/" }
log = "0.4"
mime = "0.3"
multipart = { version = "0.17", features = ["server"], default-features = false }
serde = "1.0"
serde_urlencoded = "0.7"
thiserror = "1.0"

[dev-dependencies]
pretty_env_logger = "0.4"
serde = { version = "1.0", features = ["derive"] }
trybuild = "1.0"
