# -*- eval: (cargo-minor-mode 1) -*-

[package]
name = "gotham_formdata_derive"
version = "0.0.1"
authors = ["Dominic Meiser <git@msrd0.de>"]
edition = "2018"
description = "Form data parsing for the gotham web framework - Derive macros"
license = "Apache-2.0"
repository = "https://github.com/msrd0/gotham_formdata"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "1.0", features = ["derive"] }
