name: Rust
on:
  push:
    branches: [master]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@1.42.0
      
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo
            target
          key: ${{ runner.os }}-cargo-1.42 }}
      
      - run: cargo test -- --skip trybuild_ui
  
  trybuild:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.48.0
      
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo
            target
          key: ${{ runner.os }}-cargo-1.48 }}
      
      - run: cargo test -- trybuild_ui
  
  coverage:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
      
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo
            target
          key: ${{ runner.os }}-cargo-tarpaulin }}
      
      - run: cargo install cargo-tarpaulin
      
      - run: |
          cargo tarpaulin -v \
          	--target-dir target/tarpaulin \
          	--workspace \
          	--all-features \
          	--exclude-files 'cargo/*' \
          	--exclude-files 'derive/*' \
          	--exclude-files 'target/*' \
          	--ignore-panics --ignore-tests \
          	--out Html --out Json \
          	-- --skip trybuild_ui
      
      - uses: actions/upload-artifact@v2
        with:
          name: tarpaulin-report
          path: |
            tarpaulin-report.json
            tarpaulin-report.html
  
  doc:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
      
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo
            target
          key: ${{ runner.os }}-cargo-doc }}
      
      - run: cargo doc --workspace --all-features
      
      - run: tar cfJ rustdoc.tar.xz target/doc/
      - uses: actions/upload-artifact@v2
        with:
          name: rustdoc
          path: rustdoc.tar.xz
  
  rustfmt:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - run: cargo fmt -- --check
  
  readme:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo install cargo-readme
      - run: cargo readme >README.md.new
      - run: diff README.md README.md.new
  
  pages:
    runs-on: ubuntu-20.04
    needs: [coverage, doc]
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
        with:
          ref: gh-pages
      
      - uses: actions/download-artifact@v2
        with:
          name: rustdoc
      
      - uses: actions/download-artifact@v2
        with:
          name: tarpaulin-report
      
      - run: |
          test ! -d ./doc || rm -r ./doc
          tar xfJ rustdoc.tar.xz --strip-components=1
          rm rustdoc.tar.xz
          date >./doc/.timestamp
          
          coverage=$(jq '.files | { covered: map(.covered) | add, coverable: map(.coverable) | add } | .covered / .coverable * 10000 | round | . / 100' tarpaulin-report.json)
          color=$([[ $coverage < 90 ]] && printf yellow || printf brightgreen)
          wget -qO coverage.svg "https://img.shields.io/badge/coverage-$coverage%25-$color"
          
          git add ./doc
          git status
      
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "GitHub Pages for ${{ github.sha }}"
